### ISSUE TITLE
Add Liberator Method for barcode lookup

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/voyager_helpers#10]
Add a liberator method that wraps the "record_ids_for_barcode" query added in c92f9c4967b29dbb00e7e49239392e703ddf8a37. Also add specs to these these new additions. @mzelesky do you want to give this a try later this week?

**Comment by mzelesky** [comment]
That sounds good to me. I did a spec last week for the invalid ASCII character problem, so I should be able to do a spec for this.
