### ISSUE TITLE
Add find_by_id method

### ISSUE THREAD

**Issue by christinach** [pulibrary/voyager_helpers#118]
Move the find_by_id logic from https://github.com/pulibrary/marc_liberation/blob/be62263a213df38810ac676c6844aca12cb70390/app/controllers/bibliographic_controller.rb#L106 into voyager_helpers.

see https://github.com/pulibrary/marc_liberation/issues/786

**Comment by hackartisan** [comment]
I don't think this needs to be pushed all the way down into voyager_helpers. We'll be retiring this codebase and the marc_liberation adapter that uses it soon anyway.
