### ISSUE TITLE
Barcode Lookup Subfield Mismatch

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/voyager_helpers#56]
The values currently output in subfields x and z in the 876 field produced for an individual item record in the record lookup by barcode should be switched.

* Collection Group Designation should be in subfield z 
* Customer Code should in subfield x

Flip these two values:
https://github.com/pulibrary/voyager_helpers/blob/01efacb5001e08a8dac448162d3b2d00a4e3fcfb/lib/voyager_helpers/liberator.rb#L741-L742

**Comment by mzelesky** [comment]
This is no longer an issue, right?

**Comment by kevinreiss** [comment]
Yes, HTC fixed this on their end.
