### ISSUE TITLE
Disambiguate availability status

### ISSUE THREAD

**Issue by tampakis** [pulibrary/voyager_helpers#72]
Refactor [get_availability](https://github.com/pulibrary/voyager_helpers/blob/4dab2239e172138ead81e369cf77587db5149bf3/lib/voyager_helpers/liberator.rb#L177-L184) so that `:status` only contains an array of Voyager item statuses and that order status is a separate property. Requires updates to Marc Liberation.

**Comment by mzelesky** [comment]
Closed by #71.
